<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_ChooseFIle</name>
   <tag></tag>
   <elementGuidId>7772678b-6aef-421e-94b7-3cfd29ad1343</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ufile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ufile']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a8393ec5-d32b-4b00-9bb1-2a1b05d1f0c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>83288a2c-d6ab-4d95-aefe-1c6eb69b62c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ufile</value>
      <webElementGuid>3c2bf99f-a412-4ae2-8b7a-800a865bb69f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ufile</value>
      <webElementGuid>aa494fd6-7e17-48ac-bffb-3c4420928807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ufile&quot;)</value>
      <webElementGuid>6049363d-a701-4b2f-93db-fa9bab9ad9db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ufile']</value>
      <webElementGuid>53b78529-7753-4477-99d7-6b91b5bd76ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmEmpAttachment']/fieldset/ol/li[2]/input[2]</value>
      <webElementGuid>3220f42c-223c-4372-bcf4-6f5fa7d5fcc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/input[2]</value>
      <webElementGuid>844e531f-fde5-444a-9be5-c30951b275f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'ufile' and @id = 'ufile']</value>
      <webElementGuid>68a67432-6b7a-46d4-a589-5fc92445e77c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
