<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Comment</name>
   <tag></tag>
   <elementGuidId>2700cfe9-96ec-419e-9e93-ea5b680e0bb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtAttDesc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='txtAttDesc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4ad5a928-0da7-411c-ad85-14985b2726e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtAttDesc</value>
      <webElementGuid>9ee8ac20-cf9b-4480-b28a-765ee2dc62e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtAttDesc</value>
      <webElementGuid>6a8d7f62-22f3-4af6-8f20-765cf667a117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>9c438fde-c66c-4a87-a6fc-20a76c3f6c2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>cb77da58-0dc6-4296-8225-bda490c3c3e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtAttDesc&quot;)</value>
      <webElementGuid>495e3d35-0314-4da4-9425-dd8268a63592</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='txtAttDesc']</value>
      <webElementGuid>2faa993f-2cf6-4a06-88f4-74241e0831b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmEmpAttachment']/fieldset/ol/li[3]/textarea</value>
      <webElementGuid>16f0b7fb-ff57-4d1c-8996-8177aea0d712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>e403b2bf-444f-49c8-b2dd-c073bdf3a60f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'txtAttDesc' and @id = 'txtAttDesc']</value>
      <webElementGuid>3c86138d-a083-41b9-ade8-3b1834e595c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
