<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Password</name>
   <tag></tag>
   <elementGuidId>d4929902-13fc-45c3-8322-b59f1e76a283</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#systemUser_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='systemUser_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea03ed1e-2daa-4ca3-80cc-71c673ac9527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInputText password validation-error</value>
      <webElementGuid>367bb486-a967-42d4-8a97-4ee15d39c1d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ebec1820-67d9-4437-8588-ab0703c65465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlenght</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>9658b0da-2fc6-4b67-b2a0-c5a55791a2cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>7cb4f9c2-1134-4f19-bc89-04e7d26b7a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>3bccdae6-c68e-4cd2-9044-df807a72fff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>systemUser[password]</value>
      <webElementGuid>19925252-2304-45fd-b6ac-e7514dc60754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>systemUser_password</value>
      <webElementGuid>d0f5e482-87ca-4683-9c5d-e6615cc00542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;systemUser_password&quot;)</value>
      <webElementGuid>ed465999-d75b-4184-bf4f-5bc8c74fef0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='systemUser_password']</value>
      <webElementGuid>ecf0d22f-cfab-4c59-ae09-851df786f17e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSystemUser']/fieldset/ol/li[6]/input</value>
      <webElementGuid>3c6f0c45-7ecd-43b2-ba6f-3927bd3f997d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/input</value>
      <webElementGuid>9225c8a7-3d1f-46d4-81d2-eade95f5dd45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'systemUser[password]' and @id = 'systemUser_password']</value>
      <webElementGuid>e41dc10c-5b8c-49b6-ad29-19b5c97cb068</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
