<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Username</name>
   <tag></tag>
   <elementGuidId>e056664a-73a6-4f06-95e8-8ce332cc93af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#systemUser_userName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='systemUser_userName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>80fb5b12-5825-4e1a-a5aa-a51bdc437059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInputText validation-error</value>
      <webElementGuid>69ad17c2-ff14-43f6-8435-ae710ed71555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>03d75b8a-d080-4876-8eab-d9385a3cae22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2590f713-de37-4a95-b9a3-0eeeced1a22b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>systemUser[userName]</value>
      <webElementGuid>136ee387-facf-46e4-8669-b2192e71de41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>systemUser_userName</value>
      <webElementGuid>50296566-35d6-450f-8c1b-0fc52efa1d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;systemUser_userName&quot;)</value>
      <webElementGuid>0181ebfc-d9ab-4b86-8595-1aab7e5596ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='systemUser_userName']</value>
      <webElementGuid>eb6848e5-7ed3-4512-a791-54eedad423b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSystemUser']/fieldset/ol/li[3]/input</value>
      <webElementGuid>ac51febd-1337-4af4-a619-58fe3a1d82af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/input</value>
      <webElementGuid>c9220423-ed74-479b-a099-bc73d8868725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'systemUser[userName]' and @id = 'systemUser_userName']</value>
      <webElementGuid>0bef39a3-be5a-4884-bac1-a2a76bc8b0f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
