<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_ConfirmPassword</name>
   <tag></tag>
   <elementGuidId>4e66fb5e-1fe0-499f-876c-a63fde77e1b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#systemUser_confirmPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='systemUser_confirmPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f28f371c-3106-43d4-b617-4f4d89dfb245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInputText password valid</value>
      <webElementGuid>c03e27a2-185e-429f-b53a-6514750bd7dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>cb428b5c-091b-4060-b504-05c26c4a770a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>2b5f56af-d2e0-424d-9024-8d217fc31961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>3f9bca0a-cc38-4e2f-93fa-fad839aca35d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>systemUser[confirmPassword]</value>
      <webElementGuid>505e43ed-77b2-45aa-883d-f0b584f08396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>systemUser_confirmPassword</value>
      <webElementGuid>38b2adf0-c023-4bf6-8095-6a8fb81467dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;systemUser_confirmPassword&quot;)</value>
      <webElementGuid>894174d5-a388-41a6-bbc2-4e2d4556d114</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='systemUser_confirmPassword']</value>
      <webElementGuid>97c946f4-970e-4056-8783-12c5aedb27f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSystemUser']/fieldset/ol/li[7]/input</value>
      <webElementGuid>c030bf42-0333-46f2-aaad-b875b4ab0b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/input</value>
      <webElementGuid>3343d690-7836-4010-b322-ee6531bc5600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'systemUser[confirmPassword]' and @id = 'systemUser_confirmPassword']</value>
      <webElementGuid>198415a2-6c3b-41c0-ba45-9555e387cb2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
