name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v3.0
      with:
          version: '7.5.5'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -runMode=console -testSuitePath="Test Suites/My Info" -apiKey= ${{ secrets.API_KEY }} -browserType="Chrome (headless)" -executionProfile="default" --config -webui.autoUpdateDrivers=true' 
