name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v3.0
      with:
          version: '7.5.5'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -runMode=console -testSuiteCollectionPath="Test Suites/S1 Login-SauceDemo" -apiKey= ${{ secrets.API_KEY }} -browserType="Chrome (headless)" -executionProfile="default" -orgID=653509 -testOpsProjectId=1207418 --config -webui.autoUpdateDrivers=true -proxy.auth.option=USE_SYSTEM -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true' 
