name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v3.0
      with:
          version: '7.5.5'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -runMode=console -projectPath="D:\Katalon Project\Demo Web\Day 1 Web-Based.prj" -retry=0 -testSuitePath="Test Suites/S1 Login-SauceDemo" -browserType="Remote" -executionProfile="default" -apiKey=${{ secrets.API_KEY }} -orgID=653509 -testOpsProjectId=1236067 --config -proxy.auth.option=USE_SYSTEM -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true' 
